### ISSUE TITLE
Allow user to share the given article. (social network sharing feature.)

### ISSUE THREAD

**Issue by sansarp** [leapfrogtechnology/zoomify-child#7]
Social sharing plugins could be used. Social sharing: facebook, twitter, linkedin etc.

**Comment by sansarp** [comment]
This feature has been implemented. Feedbacks are welcome. If fine somebody can close this issue. :)

**Comment by poudelprakash** [comment]
I think it looks fine!

**Comment by balabhadra** [comment]
Good job. 

Few suggestions:
 1. I suggest to not include it in the home page.
 2. Also let's put it in only after the blog post rather than keep it floating in the page itself. Looks a bit spammy at the moment
3. Color does not match with with our theme. Black/White/Gray coloring would better suit our theme.

**Comment by balabhadra** [comment]
This seems pretty popular for social media: 
https://wordpress.org/plugins/ultimate-social-media-plus

**Comment by sansarp** [comment]
Thank you for the suggestions. Will look into it.
